services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file: .env
    environment:
      MYSQL_DATABASE: shopping
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/init:/docker-entrypoint-initdb.d  # Mount init scripts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: shopping_api
    depends_on:
      db:
        condition: service_healthy

#  web:
#    build:
#      context: ./ui
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"
#    depends_on:
#      - api
volumes:
  mysql_data: