services:
  api:
    container_name: web_service_api_test
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - COMPOSE_BAKE=true
    volumes:
      - .:/app
      - ~/.m2:/root/.m2  # Cache Maven dependencies
      - ./target/surefire-reports:/app/target/surefire-reports
      - ./target/site/jacoco:/app/target/site/jacoco
    command: [ "./mvnw", "-X", "verify"]
