# Build stage
FROM eclipse-temurin:17-jdk-jammy as build
WORKDIR /app
COPY . .
RUN chmod +x mvnw
RUN ./mvnw verify

# Runtime stage
FROM eclipse-temurin:17-jre-jammy
COPY --from=build /app/target/*.jar app.jar